data from: https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020?select=drivers.csv

contains data from 1950-2024

F1 has had many different points systems throughout the years. The current point system (25 points for 1st cascading down to 1 point for 10th) started in 2010. While there have been minor changes to the points system since, the distribution of points for race finishes has remained the same. This will be treated as the modern era for F1.

From 1950 to 1959 F1 awarded points to the top 5 drivers.

From 1961 to 2002 F1 awarded points to the top 6 drivers.

From 2003 to 2009 F1 awarded points to the top 8 drivers.

While there were minor changes in between as periods, the distribution of points for race finishes has remained the same.

A player's elo only changes when they win or lose, gaining and losing elo respectively. While the first place driver is the sole winner, elo will be awarded to all points winning drivers. Their elo gain will be adjusted for their finishing postion. This applies to drivers outside of the points as well. For exmaple, a driver that barely missed out on points will lose less elo than one who finished near the end of the grid.

get win prob by grid pos?

In [1]:
import pandas as pd
import numpy as np

In [2]:
driver_standings_df = pd.read_csv('driver_standings.csv')
driver_standings_df

,driverStandingsId,raceId,driverId,points,position,positionText,wins
0,1,18,1,10.0,1,1,1
1,2,18,2,8.0,2,2,0
2,3,18,3,6.0,3,3,0
3,4,18,4,5.0,4,4,0
4,5,18,5,4.0,5,5,0
...,...,...,...,...,...,...,...
34590,72867,1132,839,3.0,18,18,0
34591,72868,1132,842,6.0,15,15,0
34592,72869,1132,822,0.0,21,21,0
34593,72870,1132,858,0.0,20,20,0
34594,72871,1132,860,6.0,14,14,0

In [3]:
drivers_elo_df = pd.read_csv('drivers.csv')
drivers_elo_df = drivers_elo_df.drop(['number', 'code', 'dob', 'nationality', 'url'], axis=1)
drivers_elo_df['elo'] = [1000] * len(drivers_elo_df.index)
drivers_elo_df

     driverId   driverRef  forename     surname   elo
0           1    hamilton     Lewis    Hamilton  1000
1           2    heidfeld      Nick    Heidfeld  1000
2           3     rosberg      Nico     Rosberg  1000
3           4      alonso  Fernando      Alonso  1000
4           5  kovalainen    Heikki  Kovalainen  1000
..        ...         ...       ...         ...   ...
854       856    de_vries      Nyck    de Vries  1000
855       857     piastri     Oscar     Piastri  1000
856       858    sargeant     Logan    Sargeant  1000
857       859      lawson      Liam      Lawson  1000
858       860     bearman    Oliver     Bearman  1000

[859 rows x 5 columns]

In [4]:
races_df = pd.read_csv('races.csv')
races_df = races_df.drop(['date', 'time', 'url', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time'], axis=1)
races_df.sort_values(['year', 'round'])

      raceId  year  round  circuitId                    name
832      833  1950      1          9      British Grand Prix
833      834  1950      2          6       Monaco Grand Prix
834      835  1950      3         19        Indianapolis 500
835      836  1950      4         66        Swiss Grand Prix
836      837  1950      5         13      Belgian Grand Prix
...      ...   ...    ...        ...                     ...
1120    1140  2024     20         32  Mexico City Grand Prix
1121    1141  2024     21         18    São Paulo Grand Prix
1122    1142  2024     22         80    Las Vegas Grand Prix
1123    1143  2024     23         78        Qatar Grand Prix
1124    1144  2024     24         24    Abu Dhabi Grand Prix

[1125 rows x 5 columns]

In [5]:
qualifying_df = pd.read_csv('qualifying.csv')
qualifying_df = qualifying_df.drop(['constructorId', 'number', 'q1', 'q2', 'q3'], axis=1)
qualifying_df

       qualifyId  raceId  driverId  position
0              1      18         1         1
1              2      18         9         2
2              3      18         5         3
3              4      18        13         4
4              5      18         2         5
...          ...     ...       ...       ...
10249      10307    1132       822        16
10250      10308    1132       825        17
10251      10309    1132       839        18
10252      10310    1132       815        19
10253      10311    1132       842        20

[10254 rows x 4 columns]

In [ ]:
results_df = pd.read_csv('results.csv')
results_df